{
  "formatVersion": "1.1",
  "component": {
    "group": "vendordep",
    "module": "vendordep-plugin",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.3-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.3-SNAPSHOT.jar",
          "size": 6917,
          "sha512": "30db71043629b56197ba88cb69ed936c8c1685e4069d55b57d6a00ae3e0ceb2583184ceef430b2ac8d33925b9f9236281614ff82a8c7451423c70c478b746390",
          "sha256": "36cb7f83416d7021e5e1e5520fec9b22b1b7e3fcb65eab4ca492ecc1a8049529",
          "sha1": "c848c4c905de258916ddd912ae4d175786143b90",
          "md5": "0826d6a8ef1292b5b5c8957232511132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vendordep-plugin-1.3-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.3-SNAPSHOT.jar",
          "size": 6917,
          "sha512": "30db71043629b56197ba88cb69ed936c8c1685e4069d55b57d6a00ae3e0ceb2583184ceef430b2ac8d33925b9f9236281614ff82a8c7451423c70c478b746390",
          "sha256": "36cb7f83416d7021e5e1e5520fec9b22b1b7e3fcb65eab4ca492ecc1a8049529",
          "sha1": "c848c4c905de258916ddd912ae4d175786143b90",
          "md5": "0826d6a8ef1292b5b5c8957232511132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.3-SNAPSHOT-sources.jar",
          "url": "vendordep-plugin-1.3-SNAPSHOT-sources.jar",
          "size": 2552,
          "sha512": "bda4f73ef8f7e61f7d81a9f246674ac723078279e3ffc76c667ee55803a8ce855043fd86840fd46dae66ee1410374a597a53aedc6c08a0dfd10933bdcc18b276",
          "sha256": "e770947f030e621b1142b601211f9cdbad445cad441200135cce23b23df0edb9",
          "sha1": "c80e6b5df3e2df715c4ea130646ee9ee0560a2f7",
          "md5": "53e54676ea6f48567229ef4339bde0d1"
        }
      ]
    }
  ]
}
