{
  "formatVersion": "1.1",
  "component": {
    "group": "vendordep",
    "module": "vendordep-plugin",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.1-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.1-SNAPSHOT.jar",
          "size": 4275,
          "sha512": "6e023f54702270f274577bddc33dca3de3d15b90fe773a326a7745295c2ec6b6f69af08914a64e31731008835335750a6b07b8f131bb447e15bf1fb846aa738b",
          "sha256": "3c4349b82a54185b24bf7cd916a1fec351834c6274fe364b4b6c3cadcaaf1747",
          "sha1": "ac3512406200846bd0379fb02ca5b205e515fb16",
          "md5": "fe98bf7f07d24506853dbda32942d1ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vendordep-plugin-1.1-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.1-SNAPSHOT.jar",
          "size": 4275,
          "sha512": "6e023f54702270f274577bddc33dca3de3d15b90fe773a326a7745295c2ec6b6f69af08914a64e31731008835335750a6b07b8f131bb447e15bf1fb846aa738b",
          "sha256": "3c4349b82a54185b24bf7cd916a1fec351834c6274fe364b4b6c3cadcaaf1747",
          "sha1": "ac3512406200846bd0379fb02ca5b205e515fb16",
          "md5": "fe98bf7f07d24506853dbda32942d1ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.1-SNAPSHOT-sources.jar",
          "url": "vendordep-plugin-1.1-SNAPSHOT-sources.jar",
          "size": 1491,
          "sha512": "ae6dbc09984dc968e929d917293d6ff9e4b54a266a6cdcda6c68722052696031726d316fb3f2098f965b98fe3993f1ec25e8a490e83387c6c3955cdc94d05eb6",
          "sha256": "9a4971dc4f1b89a25f742ec6b378e9d80db695f18a690a67b2f15f29ff203d95",
          "sha1": "655e2acdef357f2b8f5b74ec24519544e65c6f39",
          "md5": "4c7eb60becca7dce0d7979d227f1bc5c"
        }
      ]
    }
  ]
}
