{
  "formatVersion": "1.1",
  "component": {
    "group": "vendordep",
    "module": "vendordep-plugin",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "size": 4068,
          "sha512": "24d5be0f817f265bca8696e5c8cde5161756e6d282593ebafcfb6a16ce68160d7bdcdd9867bccd774074142cb80d40d02aa1a1cda592b16a03a04a060064b549",
          "sha256": "7df2e7dcb43b39b7d1ff4680ec4f90c26429858553924af7a4537a3c304984b0",
          "sha1": "61f191cf55afafb87efea693bdb25efd462c2704",
          "md5": "95c1a9ed974c56cc9e6f036ef89b25ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "size": 4068,
          "sha512": "24d5be0f817f265bca8696e5c8cde5161756e6d282593ebafcfb6a16ce68160d7bdcdd9867bccd774074142cb80d40d02aa1a1cda592b16a03a04a060064b549",
          "sha256": "7df2e7dcb43b39b7d1ff4680ec4f90c26429858553924af7a4537a3c304984b0",
          "sha1": "61f191cf55afafb87efea693bdb25efd462c2704",
          "md5": "95c1a9ed974c56cc9e6f036ef89b25ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT-sources.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT-sources.jar",
          "size": 1440,
          "sha512": "d74ee8074b934970cc5e0720515b9d843621972ddd13f9814022a2c7f7675ff4621fd55b731862dfa06cb7d20650f152015e713d64ba9f8264a1245eb8e68b88",
          "sha256": "df63b1a7b820841a9056be3cd1e102c6656a7ad41e10b28cc13f37ba8e6a798e",
          "sha1": "8ad074d5bfc9ae401a2df1f36b4e47836ad4a31a",
          "md5": "eb169d3453ba9e4a0079674bcf9e832f"
        }
      ]
    }
  ]
}
