{
  "formatVersion": "1.1",
  "component": {
    "group": "vendordep",
    "module": "vendordep-plugin",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "size": 4082,
          "sha512": "6cb351c1c8866082dd39d9fe84ded37f581e64f5eb12bda92a9587d973025f5fa04f5c1b35f31a8eef16e7f648f7a335570d149ba660e5a9ad06405ac1a2d082",
          "sha256": "338395695ca3153630c25d332ef4edfaf4fc3e67d906e281ea486f117d958332",
          "sha1": "d6a312ea74a8d2756f6d13e2bbbef1c99354d691",
          "md5": "aa682f2cbda123474b04f2fee79452dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT.jar",
          "size": 4082,
          "sha512": "6cb351c1c8866082dd39d9fe84ded37f581e64f5eb12bda92a9587d973025f5fa04f5c1b35f31a8eef16e7f648f7a335570d149ba660e5a9ad06405ac1a2d082",
          "sha256": "338395695ca3153630c25d332ef4edfaf4fc3e67d906e281ea486f117d958332",
          "sha1": "d6a312ea74a8d2756f6d13e2bbbef1c99354d691",
          "md5": "aa682f2cbda123474b04f2fee79452dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.0-SNAPSHOT-sources.jar",
          "url": "vendordep-plugin-1.0-SNAPSHOT-sources.jar",
          "size": 1440,
          "sha512": "d74ee8074b934970cc5e0720515b9d843621972ddd13f9814022a2c7f7675ff4621fd55b731862dfa06cb7d20650f152015e713d64ba9f8264a1245eb8e68b88",
          "sha256": "df63b1a7b820841a9056be3cd1e102c6656a7ad41e10b28cc13f37ba8e6a798e",
          "sha1": "8ad074d5bfc9ae401a2df1f36b4e47836ad4a31a",
          "md5": "eb169d3453ba9e4a0079674bcf9e832f"
        }
      ]
    }
  ]
}
