{
  "formatVersion": "1.1",
  "component": {
    "group": "vendordep",
    "module": "vendordep-plugin",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.2-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.2-SNAPSHOT.jar",
          "size": 6683,
          "sha512": "f6edec4c0b1e0cfd7ad06d5abf27daf0825b8c15c35764b6d39be9ccdf381e9fa8844bd3db75831e707704899a0213eee368c03d50de811aafff14db0038c68e",
          "sha256": "ff81ad93a30a4a8a9aaca98b84224cfaff51913918013374da319f32074e0855",
          "sha1": "802e92c402ba8bd232218bdbe0e6ee2e6fc0bcd8",
          "md5": "3976794c74d3949794a6ceef67646962"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vendordep-plugin-1.2-SNAPSHOT.jar",
          "url": "vendordep-plugin-1.2-SNAPSHOT.jar",
          "size": 6683,
          "sha512": "f6edec4c0b1e0cfd7ad06d5abf27daf0825b8c15c35764b6d39be9ccdf381e9fa8844bd3db75831e707704899a0213eee368c03d50de811aafff14db0038c68e",
          "sha256": "ff81ad93a30a4a8a9aaca98b84224cfaff51913918013374da319f32074e0855",
          "sha1": "802e92c402ba8bd232218bdbe0e6ee2e6fc0bcd8",
          "md5": "3976794c74d3949794a6ceef67646962"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vendordep-plugin-1.2-SNAPSHOT-sources.jar",
          "url": "vendordep-plugin-1.2-SNAPSHOT-sources.jar",
          "size": 2489,
          "sha512": "906b4db78ca7e2c706e977048191cdd83e70a5cd09c756d9b66d4304bf262fd1b3526eb6f959dade10f86128299a9dedab54689b6ac329eaae3c455df09d08e8",
          "sha256": "83ed2fb04f787502258fb38568e807963a20883154ff2a370f62397ff15eb0b9",
          "sha1": "d2af30284d8722f466452b7b03598a35016acf90",
          "md5": "3721ef03462ed30817588f311c72d95a"
        }
      ]
    }
  ]
}
